### ISSUE TITLE
403 error from server

### ISSUE THREAD

**Issue by ghaiklor** [jamon/playmusic#27]
When I'm trying to connect to the Google Play Music I've got the following error:

```
[Error: Unable to create oauth tokenError: 403 error from server]
```

Here is my code:

```javascript
var PlayMusic = require('playmusic');
var pm = new PlayMusic();
pm.init({email: "mail@gmail.com", password: "password"}, function(err) {
        if(err) console.error(err);
        pm.getAllTracks(function(err, library) {
                var song = library.data.items.pop();
                console.log(song);
                pm.getStreamUrl(song.id, function(err, streamUrl) {
                        console.log(streamUrl);
                    });
            });
    });
```

**Comment by jamon** [comment]
what version are you running?

**Comment by ghaiklor** [comment]
2.0.3. Just installed from npm.

**Comment by IncoCode** [comment]
@ghaiklor did you enable 2-step verification in your google account? You should disable it.
The following works fine for me:
```js
var pm = new PlayMusic();

var obj = {
    email: 'email',
    password: 'pass'
};
new Promise(function (resolve, reject) {
    pm.login(obj, function (err, obj) {
        if (err) return reject(err);
        resolve(obj);
    });
})
.then(function (obj) {
    return new Promise(function (resolve, reject) {
        pm.init(obj, function (err) {
            if (err) return reject(err);
            resolve();
        })
    })
})
.then(function () {
    return new Promise(function (resolve, reject) {
        pm.getPlayListEntries(function (err, body) {
            if (err) return reject(err);
            resolve(body.data.items);
        })
    })
})
.then(function (playlistEntries) {
    console.log(playlistEntries);
})
.catch(console.log)
```

**Comment by ghaiklor** [comment]
I have disabled two step verification.

**Comment by 96AA48** [comment]
I've been getting this issue randomly every now and again, any progress with understanding what this issue is? I also have no two-step verification.

**Comment by misantronic** [comment]
I get the same error on 2.0.3

**Comment by 96AA48** [comment]
@misantronic I've got the same thing now that I think of it. Just thought that was related to some other google auth thing. Can you still use the `playmusic` package without it blocking completely?

**Comment by misantronic** [comment]
@96AA48 nope, cannot use anything of the package :( about 2 weeks ago I ran a test and I was able to retrieve the playlists with the same google account on another device. Now, nothing.

**Comment by 96AA48** [comment]
@misantronic Same here, I've been using it for a cli music player called [gplayer](http://npmjs.org/gmplayer), had a lot of people excited but for some reason it stopped working 2 weeks ago as well.. Summoning @jamon, please help!

**Comment by jamon** [comment]
Interesting.  These issues seem to be account specific, some people have
issues and others don't.  I'll try to figure out what's going on tonight.

**Comment by kudos** [comment]
@jamon pretty sure it's the "Allow less secure apps" setting [here]( https://myaccount.google.com/security#signin). It has to be set to "ON".

Mine somehow got changed to "OFF". I pay for an account for my mom to use on her phone, that I also use for https://match.audio, so I suspect she got prompted on her phone when she upgraded to Marshmallow. The timing makes sense to me.

**Comment by 96AA48** [comment]
@kudos I've enabled that option as well, and the issue seems to have disappeared. However, we shouldn't compromise on security. Is there any way we can fix the issue without enabling "Allow less secure apps"?

**Comment by kudos** [comment]
@96AA48 someone would need to reverse engineer the "more secure apps" mechanism. I intentionally use an account I don't care about not just for this, but also in case I accidentally slam the API and get my main account disabled by Google.

**Comment by jamon** [comment]
I did actually start down this path, so it's less far than it seems, and some of the play music libs for other languages support it.  The token style authentication where you call pm.login to create a master token (or pull the one off your phone) might actually bypass this issue as well.  I ran into some issues implementing the encryption that other libraries do for user/pass when generating the token, but I think post-token the flows are the same.  My gut feeling is that my lack of encryption on the user/pass is why it may require allowing less secure apps.

**Comment by bimusiek** [comment]
We put a lot of effort into investigatin this issue, if you want to make sure user can login, just follow steps from https://stampapp.io/faq.html#collapsefaq-google-music

**Comment by jamon** [comment]
I setup a new account for myself and did not enable less secure logins and it seemed to work.  I'd be interested in whether people are still seeing this issue.  Let me know if you are.

**Comment by LudekStoklasa** [comment]
I am unable to get the stream URL for the all access songs (getting 403), user uploaded songs works fine. Is it possible that that hash calculations for slt/sig are no longer valid?

pm.getStreamUrl("97736b8e-eb85-3a90-b78a-72efd39b516e", console.log);
=> works

pm.getStreamUrl("T3tc44gorljz5onziramlzwbvza", console.log);
=> getting 403

**Comment by adeelaimviz** [comment]
I am getting the same issue but only on my production server. My local machine authenticates fine. When I deploy it to our US server and try to authenticate using the same account, it does not work. @jamon any idea about this?

**Comment by breadlesscode** [comment]
Is app spefific password working?

https://myaccount.google.com/apppasswords

**Comment by bimusiek** [comment]
@adeelaimviz Please paste an error here, we realized yesterday that sometimes Google returns an error with authentication link that you have to open to authenticate account in the web browser. Especially when you connect from different country to your account.

**Comment by adeelaimviz** [comment]
@bimusiek I dont see any link in the response. I also tried removing the country from the generated post URL and tried changing the sdk version and it still worked locally, but didn't work on my US server. 

Strangely, the account is US based, and I am using it from Pakistan. I had to open it from my local browser to make it work locally, but its already being used in US.

![screen shot 2017-05-15 at 4 46 56 pm](https://cloud.githubusercontent.com/assets/26980792/26056412/ac192d16-398e-11e7-9184-6ee6ef9271f3.png)

**Comment by bimusiek** [comment]
The screenshot you posted does not print a response from the Google. It is just an error that was thrown by this lib.

**Comment by adeelaimviz** [comment]
You're right, I am getting this following response from Google with a URL on my 2nd local computer

Error=NeedsBrowser
Url=[ I removed the URL ]
ErrorDetail=To access your account, you must sign in on the web. Touch Next to start browser sign-in.

The problem is, I cannot login on the server using those details. I am trying to get this work by user inputting the email address and password himself, and apparently it seems it won't work if the country is different or even the device is new.

Is there any workaround

**Comment by kudos** [comment]
See this thread and try what it suggests (2FA and app specific passwords): https://github.com/simon-weber/gmusicapi/issues/373

**Comment by deviantintegral** [comment]
I'm no longer able to authenticate, even with an app-specific password as of a week or two ago.

**Comment by IamCarbonMan** [comment]
Same deal here. I'm using app-specific passwords and getting 403s consistently, although Google isn't sending me emails about suspicious activity like they usually do when 2FA stuff doesn't work.

**Comment by iKethavel** [comment]
hello everyone! Do you have an idea how to authorize using this plugin?

**Comment by jamon** [comment]
Try using the .login() method with your app password to create a master token, then try using .init with the master token and your username, with no password.

**Comment by iKethavel** [comment]
var pm = new PlayMusic();

    var opt = {
        email: MY_MAIL,
        password: MY_PASS
    };

    pm.login(opt, function (err, data) {
        if(err) console.log(err);
        else console.log(data);

    })

hello again, i'm trying to use login() method first but i have a similar error like in init() method
<details> 
  <summary>403 Error </summary>
   { Error: 403 error from server
    at IncomingMessage.<anonymous> (E:\WebProjects\frontend\FreezePro\NodeTest\node_modules\playmusic\play.js:72:23)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
  statusCode: 403,
  response:
   IncomingMessage {
     _readableState:
      ReadableState {
        objectMode: false,
        highWaterMark: 16384,
        buffer: [Object],
        length: 0,
        pipes: null,
        pipesCount: 0,
        flowing: true,
        ended: true,
        endEmitted: true,
        reading: false,
        sync: false,
        needReadable: false,
        emittedReadable: false,
        readableListening: false,
        resumeScheduled: false,
        defaultEncoding: 'utf8',
        ranOut: false,
        awaitDrain: 0,
        readingMore: false,
        decoder: [Object],
        encoding: 'utf8' },
     readable: false,
     domain: null,
     _events: { end: [Object], data: [Function], error: [Function] },
     _eventsCount: 3,
     _maxListeners: undefined,
     socket:
      TLSSocket {
        _tlsOptions: [Object],
        _secureEstablished: true,
        _securePending: false,
        _newSessionPending: false,
        _controlReleased: true,
        _SNICallback: null,
        servername: null,
        npnProtocol: false,
        alpnProtocol: false,
        authorized: true,
        authorizationError: null,
        encrypted: true,
        _events: [Object],
        _eventsCount: 10,
        connecting: false,
        _hadError: false,
        _handle: null,
        _parent: null,
        _host: 'android.clients.google.com',
        _readableState: [Object],
        readable: false,
        domain: null,
        _maxListeners: undefined,
        _writableState: [Object],
        writable: false,
        allowHalfOpen: false,
        destroyed: true,
        _bytesDispatched: 403,
        _sockname: null,
        _pendingData: null,
        _pendingEncoding: '',
        server: undefined,
        _server: null,
        ssl: null,
        _requestCert: true,
        _rejectUnauthorized: true,
        parser: null,
        _httpMessage: [Object],
        read: [Function],
        _consuming: true,
        write: [Function: writeAfterFIN],
        _idleNext: null,
        _idlePrev: null,
        _idleTimeout: -1 },
     connection:
      TLSSocket {
        _tlsOptions: [Object],
        _secureEstablished: true,
        _securePending: false,
        _newSessionPending: false,
        _controlReleased: true,
        _SNICallback: null,
        servername: null,
        npnProtocol: false,
        alpnProtocol: false,
        authorized: true,
        authorizationError: null,
        encrypted: true,
        _events: [Object],
        _eventsCount: 10,
        connecting: false,
        _hadError: false,
        _handle: null,
        _parent: null,
        _host: 'android.clients.google.com',
        _readableState: [Object],
        readable: false,
        domain: null,
        _maxListeners: undefined,
        _writableState: [Object],
        writable: false,
        allowHalfOpen: false,
        destroyed: true,
        _bytesDispatched: 403,
        _sockname: null,
        _pendingData: null,
        _pendingEncoding: '',
        server: undefined,
        _server: null,
        ssl: null,
        _requestCert: true,
        _rejectUnauthorized: true,
        parser: null,
        _httpMessage: [Object],
        read: [Function],
        _consuming: true,
        write: [Function: writeAfterFIN],
        _idleNext: null,
        _idlePrev: null,
        _idleTimeout: -1 },
     httpVersionMajor: 1,
     httpVersionMinor: 1,
     httpVersion: '1.1',
     complete: true,
     headers:
      { 'content-type': 'text/plain; charset=utf-8',
        'cache-control': 'no-cache, no-store, max-age=0, must-revalidate',
        pragma: 'no-cache',
        expires: 'Mon, 01 Jan 1990 00:00:00 GMT',
        date: 'Tue, 27 Jun 2017 15:37:59 GMT',
        'x-content-type-options': 'nosniff',
        'x-frame-options': 'SAMEORIGIN',
        'x-xss-protection': '1; mode=block',
        server: 'GSE',
        'alt-svc': 'quic=":443"; ma=2592000; v="39,38,37,36,35"',
        'accept-ranges': 'none',
        vary: 'Accept-Encoding',
        connection: 'close' },
     rawHeaders:
      [ 'Content-Type',
        'text/plain; charset=utf-8',
        'Cache-Control',
        'no-cache, no-store, max-age=0, must-revalidate',
        'Pragma',
        'no-cache',
        'Expires',
        'Mon, 01 Jan 1990 00:00:00 GMT',
        'Date',
        'Tue, 27 Jun 2017 15:37:59 GMT',
        'X-Content-Type-Options',
        'nosniff',
        'X-Frame-Options',
        'SAMEORIGIN',
        'X-XSS-Protection',
        '1; mode=block',
        'Server',
        'GSE',
        'Alt-S
</details>

**Comment by ewnd9** [comment]
FWIW Basic example from https://github.com/simon-weber/gmusicapi works with an app-specific password

**Comment by Maeldor** [comment]
This used to work fine, but I am having absolutely no luck with login anymore (using my Google Account email and password, 2FA is off). Nothing has changed with my account or app, yet I'm getting 403 constantly with every attempt with either `init `or `login`.

Thought it could be an account issue, but I tried https://github.com/simon-weber/gmusicapi with a simple Python script to login and fetch some data, and it works absolutely fine (tested several times).

Also tried https://github.com/stoffern/google-play-services-auth and have the exact same issue: 403 all the time.

Is there something different between the implementation of [playmusic](https://github.com/jamon/playmusic) and [google-play-services-auth](https://github.com/stoffern/google-play-services-auth) compared to [gmusicapi ](https://github.com/simon-weber/gmusicapi) that could be causing this? Is _anyone_ able to actually use `playmusic` right now?

**Comment by Leksat** [comment]
So we need something like https://github.com/dweinstein/node-google-play/commit/e1d66c2f7f65afd8c373e65be59848de8b660be3 ?

**Comment by jamesloper** [comment]
Is anyone working on switching to `EncryptedPasswd`? If not, I could give it a go.

**Comment by jamesloper** [comment]
Got it working over here https://github.com/jamon/playmusic/compare/master...jamesloper:master

**Comment by jamon** [comment]
@jamesloper feel free to throw a PR over and I'll merge it in.

**Comment by jamesloper** [comment]
Will integrate it with my project and run some tests soon. Occasionally I am getting `bad e value` from the ssl lib when running in meteor...

**Comment by manzonif** [comment]
Work for me! 
Thanks

**Comment by Leksat** [comment]
@jamesloper's solution works for me!

**Comment by jamesloper** [comment]
So I tracked it down. My fix throws an exception in node 4 but I'll see if there's a workaround. Perhaps some crypto aspect not present in node 4 but present in node 7.

**Comment by jamon** [comment]
I've merged your branch over with the fix.  Good work!

I'll cut a release tomorrow morning with the updates.

**Comment by jamesloper** [comment]
You sure? I'll take a look tonight and see if we can do it without excluding the node 4 guys.

**Comment by kudos** [comment]
@jamesloper better to cut a release now on something broken for everyone, and sort out the folks on older node later.

**Comment by jamesloper** [comment]
Good point, cuz I wasn't sure this was confirmed broken for everyone, but that makes sense.

**Comment by kudos** [comment]
@jamesloper @jamon actually, bumping the major makes sense in case there are some folks who it still works for.

**Comment by jamon** [comment]
What do others thing about doing this as a major version bump vs a minor/patch?  Any other opinions--I'll go with what the community prefers.

**Comment by jamesloper** [comment]
I have the password encyptor working in node 4 now through node-rsa instead of crypto but I am now getting a 403 error from the server but only in node 4. If I use node 7 with same exact encryptor Google gives me the 200 and logs in perfectly.

**Comment by iKethavel** [comment]
In my case, all work fine on a local machine, but on heroku server - don't(

**Comment by jamesloper** [comment]
Alright boys, this is a doozie.

My testing script, ONLY ON node 6.0.0+ succeeded every time:

``` javascript
var PlayMusic = require('./play.js');
var pm = new PlayMusic();

pm.login({email: 'email@gmail.com', password:'pw', 'androidId':'hex_string'}, function(err, res) {
    if (err) return console.error(err);
    console.log('logged in!', res);
});
```

Under Node v4.8.4... not so much

```
Error: error:04068065:rsa routines:RSA_EAY_PUBLIC_ENCRYPT:bad e value
    at Error (native)
    at Object.publicEncrypt (crypto.js:315:12)
    at module.exports (/Users/james/test-playmusic/server/imports/playmusic/lib/encryptLogin.js:58:25)
    at PlayMusic.login (/Users/james/test-playmusic/server/imports/playmusic/play.js:192:26)
    at Object.<anonymous> (/Users/james/test-playmusic/server/imports/playmusic/test.js:4:4)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
```

I have tried ursa and node-rsa as alternatives to:

``` javascript
var encrypted = crypto.publicEncrypt(rsaPem, data);
```

eg: 

``` javascript
var encrypted = new NodeRSA(rsaPem).encrypt(data);
```

It fixed `bad e value` but gets a 403 from Google on Node 4 but actually works on Node 6.

Always got a type error in Node 5 then after switching to `new Buffer()` instead of `Buffer.from()` everywhere got past that but still get a 403.

I installed the Meteor 1.6 beta (node 6) and reverted my changes, and I think I'm good. It's possible to make this work in Node 4 but it's definitely outside of my reach. I don't usually work with cryptography.

Good night, Node 4, you have served us well.

**Comment by YashMathur** [comment]
@jamesloper I read through this thread but I can't get rid of the 403. I'm using `playmusic v2.2.1`. Here's my code:
```
var PlayMusic = require('playmusic');

var pm = new PlayMusic();
pm.init({email: "email@gmail.com", password: "password"}, function(err) {
    if (err)
      console.error(err);
})
```

And the error: `Error: Unable to create oauth tokenError: 403 error from server`

**Comment by iKethavel** [comment]
@YashMathur Hi, try this
"playmusic": "git+https://github.com/jamon/playmusic.git" in your package.json

**Comment by mferreralmirall** [comment]
Hey, I'm running into the same situation as YashMatur, and the git reference in package.json didnt fix it... is this library still working?
